.gitignore
=> [DOCS] gitignore 수정

DJ(DailyJournal)-Node/Config/config.json, DJ(DailyJournal)-Node/Models/index.js, DJ(DailyJournal)-Node/Models/journal.js, DJ(DailyJournal)-Node/Models/journalImage.js, DJ(DailyJournal)-Node/Models/summary.js, DJ(DailyJournal)-Node/Models/sync.js, DJ(DailyJournal)-Node/Models/user.js, DJ(DailyJournal)-Node/app.js
=> [FEAT] DB & BackEnd Modeling 완료

DJ(DailyJournal)-Node/Models/journal.js, DJ(DailyJournal)-Node/Models/journalImage.js, DJ(DailyJournal)-Node/Models/summary.js, DJ(DailyJournal)-Node/Models/user.js, DJ(DailyJournal)-Node/Routers/authRouter.js, DJ(DailyJournal)-Node/Routers/signRouter.js, DJ(DailyJournal)-Node/app.js
sign 로직 구현(signUp, signIn)
auth 로직 구현(JWT Token 발행)
=> [FEAT] BackEnd signRouter, authRouter 로직 구현 & user Model 수정

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
Xcode Group 폴더 추가
어떤 변경 사항이 있나요?
=> [FEAT] Xcode Groups 추가

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ColorExtension.swift
ColorExtension.swift 파일 추가
어떤 변경 사항이 있나요?
=> [FEAT] ColorExtension Add

DJ(DailyJournal)-Node/.deployment, DJ(DailyJournal)-Node/.vscode/settings.json, DJ(DailyJournal)-Node/Config/config.js, DJ(DailyJournal)-Node/Models/index.js, DJ(DailyJournal)-Node/Models/sync.js, DJ(DailyJournal)-Node/Routers/imageRouter.js, DJ(DailyJournal)-Node/Routers/journalRouter.js, DJ(DailyJournal)-Node/Routers/uploadImage.js, DJ(DailyJournal)-Node/app.js, DJ(DailyJournal)-Node/package-lock.json, DJ(DailyJournal)-Node/package.json, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
- 기존 Backend 코드를 Azure 배포에 맞게 수정.
- Azure에도 배포 완료 및 API 명세서 작성 예정
- Swift View(SignInView, TodoListView) 생성
- package.json 추가(multer-azure-blob-storage, @azure/storage-blob)
어떤 변경 사항이 있나요?
=> [FEAT] Azure AppService & DataBase 배포

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogRowView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TestModel.swift
- DailyLogViwes의 DailyLogViwe와 DailyLogRowViwe 추가
- DailyLogRowViwe에서 버튼을 눌렀을 때 추가될 템플릿 만듦
-  DailyLogViwe에서 View의 배경과 버튼을 만들고 눌렀을 때 Row가 추가 되도록 기능 추가
- Row삭제 기능 추가
어떤 변경 사항이 있나요?
=> [FEAT] DailyLogViwe add

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Resolves: #13
- TabBarView 구현 완료
- TabBarView 내부는 TabBarView1~2로 구현
- 각자 작성한 View를 TabBarView에 변경
어떤 변경 사항이 있나요?
=> [FEAT] TabBarView 구현 #13

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ColorExtension.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Resolves: #13
- TabBarView에 TodoListView 연결
- TabBarView Tag 설정
어떤 변경 사항이 있나요?
=> [FEAT] TabBarView 수정 #13

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TitleExtension.swift
- TitleExtension 추가
- DailyLogView에서 NavigationTitle의 색상 변경
어떤 변경 사항이 있나요?
=> [FEAT] TitleExtension add

DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TodoListViews/TodoListView.swift
Resolves: #20 
- 로직 구현을 위해 SignInView를 간단하게 구성했음.
어떤 변경 사항이 있나요?
=> SignInView 간단하게 구현

.gitignore, DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/BundleExtension.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/UserModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/SignService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/SignViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift, DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
Resolves: #19 
- User Model 구현
- SignService 구현
- SignViewModel 구현
- url 주소에 host는 .xcconfig로 파일 숨김 필요시 요청. 해당 값 가져올때는 bundle Extension으로 가져옴
어떤 변경 사항이 있나요?
=> [FEAT] Sign Logic 구현 #19

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/SignService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TestModel.swift
Resolves: #
- 변경 사항 내용
- Journal Service 추가
- Journal View Model 추가
어떤 변경 사항이 있나요?
=> [FEAT] Journal Logic add

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/SignViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/MainView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Resolves: #20 
- SignInView의 디자인을 Figma에 맞게 수정(추후 수정 더 필요할 수 있습니다.)
- SignIn의 결과에 따라 Alert를 띄우는 뷰 구현
어떤 변경 사항이 있나요?
=> [FEAT] SignInView 디자인 수정 및 Alert 뷰 구현

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj
Resolves: #None
- 폴더 및 파일 위치 변경
어떤 변경 사항이 있나요?
=> [REFACTOR] 파일 위치 변경

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/DetailView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/ListRowView.swift
Resolves: #
- 변경 사항 내용
어떤 변경 사항이 있나요?
=> Journal model, view, view model 수정

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/DateExtension.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/TestModeling/ImageTestView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift
Resolves: #25 
- 앨범 접근 권한 설정 완료
- 앨범에서 오늘 날짜의 이미지 가져오는 로직 구현(현재 오늘 날짜의 최근 4개의 이미지로 설정)
어떤 변경 사항이 있나요?
=> [FEAT] 앨범에서 이미지 가져오는 로직 구현

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogViews/DailyLogRowView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyLogViews/DailyLogView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignUpView.swift
Resolves: #
- DailyLogRowView의 배경색 변경
- SignUpView 주석추가
어떤 변경 사항이 있나요?
=> [FEAT] DailyLogRowView의 배경색 변경

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/TestModeling/CalendarsTestView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
Resolves: #35 
- EKEvnet타입의 Array로 받아 title을 활용
어떤 변경 사항이 있나요?
=> [FEAT] Calendars Info 가져오는 로직 구현 #35

DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListRowView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Resolves: #
- createJournalEntry 로직추가
- 주석 삭제
어떤 변경 사항이 있나요?
=> [FEAT] createJournalEntry 로직추가

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/ImagePicker.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift
Resolves: #
- Journal text editing 기능 추가
어떤 변경 사항이 있나요?
=> Journal text editing 기능 추가

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DJ(DailyJournal)-Swift/DJ(DailyJournal)/DJ_DailyJournal_App.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/BackgroundFunc.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/NotificationViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
Resolves: #37 
- Notifications 로컬 알림 기능 구현
- 일기 저장 로직은 추후 구현
어떤 변경 사항이 있나요?
=> [FEAT] Notifications 로직 연동

DJ(DailyJournal)-Node/Routers/journalRouter.js
Resolves: #
- 이미지 수정 시 데이터 잘못 담던 로직 수정
어떤 변경 사항이 있나요?
=> [FIX] Node Patch API FIX

DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Resolves: #
- JournalDetailView UI 수정
어떤 변경 사항이 있나요?
=> JournalDetailView UI 수정

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/DJ_DailyJournal_App.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/UserModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/SignService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/SignViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/ContentView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/MainView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SignViews/SignInView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift, DJ(DailyJournal)-Swift/DJ-DailyJournal--Info.plist
=> [FIX] 코드 수정 및 config 에러 해결

DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/UpdateJournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/TabBarView.swift
Resolves: #
- journalImages.count를 사용한 UpdatedJournal 모델 및 UpdatedJournalViewModel 수정
- JournalDetailView.swift의 saveChanges() 수정
- JournalListView.swift UI 수정
어떤 변경 사항이 있나요?
=> journalImages.count를 사용한 UpdatedJournal 모델 및 UpdatedJournalViewModel 수정

DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift
Resolves: #25 
- 오늘 날짜의 사진이 4장 이상일 경우 랜덤으로 사진을 가져오는 로직 추가
어떤 변경 사항이 있나요?
=> [FEAT] 앨범에서 사진 랜덤으로 가져오는 로직 추가 #25

DJ(DailyJournal)-Node/Routers/imageRouter.js, DJ(DailyJournal)-Node/Routers/journalRouter.js, DJ(DailyJournal)-Node/Routers/openaiRouter.js, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Resolves: #
- 일기 생성 시 AI Response Fetching 로직 추가
어떤 변경 사항이 있나요?
=> 일기 생성 시 AI Response Fetching 로직 추가

DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SettingViews/SettingView.swift
Resolves: #
- 로그아웃 후에 SignInView 전환
어떤 변경 사항이 있나요?
=> [FEAT] 로그아웃 후에 SignInView 전환

DJ(DailyJournal)-Node/Models/summary.js, DJ(DailyJournal)-Node/Routers/journalRouter.js, DJ(DailyJournal)-Node/Routers/main.js, DJ(DailyJournal)-Node/app.js, DJ(DailyJournal)-Swift/DJ(DailyJournal).xcodeproj/project.pbxproj, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Models/JournalModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/NetworkServices/JournalService.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalListViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SettingViews/SettingView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/SettingViews/SummarySettingView.swift
Resolves: #
- Summary 설정 관련 뷰와 로직 수정 및 구현
- 사용자가 원하는 Summary를 설정하면 해당 설정 값을 가지고 일기 내용 요약
어떤 변경 사항이 있나요?
=> [FEAT] Summary 관련 로직 수정

DJ(DailyJournal)-Node/Routers/analyzeImageFromUrl.js, DJ(DailyJournal)-Node/Routers/journalRouter.js, DJ(DailyJournal)-Node/Routers/main.js, DJ(DailyJournal)-Node/package-lock.json, DJ(DailyJournal)-Node/package.json, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Extensions/DateExtension.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/AlbumImageViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/ViewModels/JournalViewModel.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalDetailView.swift, DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Resolves: #
- 이미지를 통한 일기 내용 요약 로직 추가(Azure AI Vision 사용)
- Swift JournalView 수정(refreshable 로직 추가)
어떤 변경 사항이 있나요?
=> [FEAT] Azure AI Vision & Swift JournalView 수정

DJ(DailyJournal)-Swift/DJ(DailyJournal)/Views/DailyJournalViews/JournalListView.swift
Resolves: #
- JournalListView.swift List 역순 정렬 추가
어떤 변경 사항이 있나요?
=> JournalListView.swift List 역순 정렬 추가
